# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build -ws

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "placeholder"

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -r ./packages/client/build/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/combat-cards.duubliduu.com/client

      - name: Deploy with rsync
        run: rsync -r ./packages/server/dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/combat-cards.duubliduu.com/

      - name: Deploy package.json and lock to server
        run: rsync -r ./packages/server/package* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/combat-cards.duubliduu.com/

      - name: Start node server
        run: ssh -t  ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /var/www/combat-cards.duubliduu.com; npm i --omit=dev; npm run forever"
